export const SELECT_ORDER = 'SELECT_ORDER';
export const SELECTEDORDER_ORDER_COMPLETE_ATTEMPT = 'SELECTEDORDER_ORDER_COMPLETE_ATTEMPT';
export const SELECTEDORDER_MEALS_CHANGED = 'SELECTEDORDER_MEALS_CHANGED';
export const SELECT_ORDER_CLEAR = 'SELECT_ORDER_CLEAR';
