export const SELECTEDORDER_ADD_MEAL = 'SELECTEDORDER_ADD_MEAL';
export const SELECTEDORDER_REMOVE_MEAL = 'SELECTEDORDER_REMOVE_MEAL';
export const SELECTEDORDER_UPDATE_MEAL = 'SELECTEDORDER_UPDATE_MEAL';
export const SELECT_ORDER = 'SELECT_ORDER';
