export const ORDER_ADD_ATTEMPT = 'ORDER_ADD_ATTEMPT';
export const ORDER_ADD = 'ORDER_ADD';
export const ORDER_COMPLETE_ATTEMPT = 'ORDER_COMPLETE_ATTEMPT';
export const ORDER_COMPLETE = 'ORDER_COMPLETE';
