export const MEAL_ADD_ATTEMPT = 'MEAL_ADD_ATTEMPT';
export const MEAL_ADD = 'MEAL_ADD';
export const MEAL_UPDATE_ATTEMPT = 'MEAL_UPDATE_ATTEMPT';
export const MEAL_DELETE_ATTEMPT = 'MEAL_DELETE_ATTEMPT';
